#!/bin/bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

pbcopy < main.c
clang -fno-asm -lm -std=c11 -Wl,-stack_size,0x10000000 -O2 -o program main.c

for infile in *.in; do
    outfile="${infile/.in/.out}"
    perl -0777 -i -pe 's/\s+$//s; $_ .= "\n" unless /\n$/;' "$outfile"

    echo -n "Test $infile..."
    ./program < "$infile" > output.txt
    perl -0777 -i -pe 's/\s+$//s; $_ .= "\n" unless /\n$/;' output.txt

    if diff -q output.txt "$outfile" >/dev/null 2>&1; then
        echo -e "${GREEN} Passed.${NC}"
    else
        echo -e "${RED} Failed.${NC}"
        diff --color=auto --side-by-side --width 50 output.txt "$outfile";
    fi
done
