#!/bin/bash

filename=$(basename -- "${@: -1}")
extension="${filename##*.}"

if [ extension == 'go' ]; then
    exec nano "$@"
fi

if [ ${filename,,} == "makefile" ]; then
    exec nano "$@"
fi

exec nano -E "$@"
