#!/usr/bin/env python3

import datetime

now = datetime.datetime.now()

if 0 <= now.weekday() <= 4 and 9 <= now.hour <= 18:
    print((now - datetime.timedelta(hours=9)).isoformat())
else:
    print(now.isoformat())
